# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.




[[main]]
  name = "ğŸ”¥DeepSeek"
  weight = 10

[[main]]
  name = "å…³äºDeepSeek"
  parent = "ğŸ”¥DeepSeek"
  pageRef = "deepseek10"
  weight = 1010

[[main]]
  name = "SDeepSeekä½¿ç”¨æŒ‡å—"
  parent = "ğŸ”¥DeepSeek"
  pageRef = "deepseek20"
  weight = 1020

[[main]]
  name = "DeepSeekåº”ç”¨åœºæ™¯"
  parent = "ğŸ”¥DeepSeek"
  pageRef = "deepseek30"
  weight = 1030

[[main]]
  name = "DeepSeekèµ„æºæ±‡æ€»"
  parent = "ğŸ”¥DeepSeek"
  pageRef = "deepseek40"
  weight = 1040

[[main]]
  name = "SDeepSeekæŠ€æœ¯è§£æ"
  parent = "ğŸ”¥DeepSeek"
  pageRef = "deepseek20"
  weight = 1050

[[main]]
  name = "DeepSeekè¡Œä¸šèµ„è®¯"
  parent = "ğŸ”¥DeepSeek"
  pageRef = "deepseek30"
  weight = 1060

[[main]]
name = "çŸ¥è¯†åˆ†äº«"
pageRef = "posts"
weight = 20

[[main]]
  name = "AIå†…å®¹åˆ›ä½œ"
  parent = "çŸ¥è¯†åˆ†äº«"
  pageRef = "zmt"
  weight = 2010

[[main]]
  name = "æç¤ºè¯å·¥ç¨‹"
  parent = "çŸ¥è¯†åˆ†äº«"
  pageRef = "prompt"
  weight = 2020

[[main]]
  name = "è‡ªåŠ¨åŒ–å·¥ä½œæµ"
  parent = "çŸ¥è¯†åˆ†äº«"
  pageRef = "aiflowwork"
  weight = 2030

[[main]]
  name = "RSSè®¢é˜…æº"
  parent = "çŸ¥è¯†åˆ†äº«"
  pageRef = "rss"
  weight = 2040

[[main]]
  name = "AI SEO"
  parent = "çŸ¥è¯†åˆ†äº«"
  pageRef = "prompt"
  weight = 2050

[[main]]
name = "å­¦ä¹ ä¸“æ "
  pageRef = "columns"
weight = 30

[[main]]
  name = "AIè¶…çº§ä¸ªä½“"
  parent = "å­¦ä¹ ä¸“æ "
  pageRef = "columns/ai-super-individual/superindividual-1/"
  weight = 3010

[[main]]
  name = "ä¸€äººä¼ä¸šæ–¹æ³•è®º"
  parent = "å­¦ä¹ ä¸“æ "
  pageRef = "columns/one-person-bussiness/00-menu/"
  weight = 3020

[[main]]
  name = "å»ä¸­å¿ƒåŒ–å¹³å°æ­å»º"
  parent = "å­¦ä¹ ä¸“æ "
  pageRef = "columns/ens-ipfs-dwebsite/101-overview/"
  weight = 3030

# [[main]]
# name = "èµ„æºåº“"
# pageRef = "resume"
# weight = 40

[[main]]
name = "å…³äºæˆ‘"
pageRef = "about"
weight = 100

[[main]]
name = "èµåŠ©æ”¯æŒ"
pageRef = "reward"
weight = 50

# [[main]]
# identifier = "twitter"
# pre = "x-twitter"
# url = ""
# weight = 200

# [[main]]
# identifier = "github"
# pre = "github"
# url = ""
# weight = 300



# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "èµåŠ©"
pageRef = "reward"
weight = 10

[[footer]]
name = "å…³äº"
pageRef = "about"
weight = 100

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20

